export * from './accounts.service';
import { AccountsService } from './accounts.service';
export * from './assets.service';
import { AssetsService } from './assets.service';
export * from './banks.service';
import { BanksService } from './banks.service';
export * from './customers.service';
import { CustomersService } from './customers.service';
export * from './depositAddresses.service';
import { DepositAddressesService } from './depositAddresses.service';
export * from './externalBankAccounts.service';
import { ExternalBankAccountsService } from './externalBankAccounts.service';
export * from './externalWallets.service';
import { ExternalWalletsService } from './externalWallets.service';
export * from './identityVerifications.service';
import { IdentityVerificationsService } from './identityVerifications.service';
export * from './prices.service';
import { PricesService } from './prices.service';
export * from './quotes.service';
import { QuotesService } from './quotes.service';
export * from './rewards.service';
import { RewardsService } from './rewards.service';
export * from './symbols.service';
import { SymbolsService } from './symbols.service';
export * from './trades.service';
import { TradesService } from './trades.service';
export * from './transfers.service';
import { TransfersService } from './transfers.service';
export * from './verificationKeys.service';
import { VerificationKeysService } from './verificationKeys.service';
export * from './workflows.service';
import { WorkflowsService } from './workflows.service';
export const APIS = [AccountsService, AssetsService, BanksService, CustomersService, DepositAddressesService, ExternalBankAccountsService, ExternalWalletsService, IdentityVerificationsService, PricesService, QuotesService, RewardsService, SymbolsService, TradesService, TransfersService, VerificationKeysService, WorkflowsService];
