export * from './accounts.service';
import { AccountsService } from './accounts.service';
export * from './assets.service';
import { AssetsService } from './assets.service';
export * from './banks.service';
import { BanksService } from './banks.service';
export * from './counterparties.service';
import { CounterpartiesService } from './counterparties.service';
export * from './customers.service';
import { CustomersService } from './customers.service';
export * from './depositAddresses.service';
import { DepositAddressesService } from './depositAddresses.service';
export * from './depositBankAccounts.service';
import { DepositBankAccountsService } from './depositBankAccounts.service';
export * from './executions.service';
import { ExecutionsService } from './executions.service';
export * from './externalBankAccounts.service';
import { ExternalBankAccountsService } from './externalBankAccounts.service';
export * from './externalWallets.service';
import { ExternalWalletsService } from './externalWallets.service';
export * from './files.service';
import { FilesService } from './files.service';
export * from './identityVerifications.service';
import { IdentityVerificationsService } from './identityVerifications.service';
export * from './invoices.service';
import { InvoicesService } from './invoices.service';
export * from './paymentInstructions.service';
import { PaymentInstructionsService } from './paymentInstructions.service';
export * from './personaSessions.service';
import { PersonaSessionsService } from './personaSessions.service';
export * from './plans.service';
import { PlansService } from './plans.service';
export * from './prices.service';
import { PricesService } from './prices.service';
export * from './quotes.service';
import { QuotesService } from './quotes.service';
export * from './symbols.service';
import { SymbolsService } from './symbols.service';
export * from './trades.service';
import { TradesService } from './trades.service';
export * from './transfers.service';
import { TransfersService } from './transfers.service';
export * from './workflows.service';
import { WorkflowsService } from './workflows.service';
export const APIS = [AccountsService, AssetsService, BanksService, CounterpartiesService, CustomersService, DepositAddressesService, DepositBankAccountsService, ExecutionsService, ExternalBankAccountsService, ExternalWalletsService, FilesService, IdentityVerificationsService, InvoicesService, PaymentInstructionsService, PersonaSessionsService, PlansService, PricesService, QuotesService, SymbolsService, TradesService, TransfersService, WorkflowsService];
